apiversion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    environment: produccion
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      conteiners:
      - name: demo
        image: nginx:latest
