apiversion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    environment: desarrollo # desarrollo, produccion
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: docker.io/empresa/
