name: OPA Validation con conftest

on:
  push:
    branches: [ main ]

jobs:
  opa-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo de aplicación
        uses: actions/checkout@v4

      - name: checkout repo de políticas OPA
        uses: actions/checkout@v4
        with: 
          repository: rrodriguez942/opa-policies-central
          path: opa-policies

      - name: Instalar yq para convertir YAML a JSON
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O yq
          chmod +x yq

      - name: Convertir deployment.yaml a JSON
        run: |
          ./yq -o=json '.' deployment.yaml > deployment.json

      - name: Instalar conftest
        run: |
          wget -O - https://github.com/open-policy-agent/conftest/releases/download/v0.62.0/conftest_0.62.0_Linux_x86_64.tar.gz | tar xz
          sudo mv conftest /usr/local/bin/
          conftest --version
      
      - name: Validar deployment.json con conftest
        run: |
          conftest test deployment.json --policy opa-policies/docker --namespace docker
          conftest test deployment.json --policy opa-policies/pipeline --namespace pipelines