name: OPA Validation

on:
  push:
    branches: [ main ]

jobs:
  opa-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo de aplicación
        uses: actions/checkout@v4

      - name: Clonar repo de políticas OPA
        run: |
          git clone https://github.com/rrodriguez942/opa-policies-central.git policies

      - name: Instalar yq para convertir YAML a JSON
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O yq
          chmod +x yq
          ./yq -o=json '.' deployment.yaml > deployment.json

      - name: Descargar OPA
        run: |
          wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa
          chmod +x opa

      - name: Validar deployment.yaml con OPA
        run: |
          ./opa eval --input deployment.json --data ./policies/pipeline 'data.pipeline.deny'
          result=$(./opa eval --input deployment.json --data ./policies/pipeline 'data.pipeline.deny' --format raw)
          if [ "$result" != "[]" ]; then
            echo "Políticas OPA no cumplidas:"
            echo "$result"
            exit 1
          fi